services:
  externalapi.orchestrator:
    image: externalapiorchestrator
    restart: always
    build:
      context: .
      dockerfile: ExternalApi.Orchestrator/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    networks:
      - nw       

  internalapi01.booking:
    image: internalapi01booking
    restart: always
    build:
      context: .
      dockerfile: InternalApi01.Booking/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=postgredb;Port=5432;Username=postgres;Password=postgres;Database=bookingapi
    ports:
      - "8081:8080"
    networks:
      - nw      
  internalapi02.payment:
    image: internalapi02payment
    restart: always
    build:
      context: .
      dockerfile: InternalApi02.Payment/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sqldb;Database=PaymentDb;User Id=sa;Password=@Password581;Encrypt=False;TrustServerCertificate=True        
    ports:
      - "8082:8080"
    networks:
      - nw      
  internalapi03.notification:
    image: internalapi03notification
    restart: always
    build:
      context: .
      dockerfile: InternalApi03.Notification/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=redis:6379
    ports:
      - "8083:8080"     
    networks:
      - nw       

## DATABASES:
  postgredb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookingapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nw

  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@Password581
    ports:
      - "1433:1433"
    networks:
      - nw
 
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always
    networks:
      - nw
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"         
      - "8888:8888"         
    networks:
      - nw
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5    
    depends_on:
      jaeger:
        condition: service_started
  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - "16686:16686"       
    networks:
      - nw

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"   
    networks:
      - nw
      
volumes:
  v01:
    driver: local
  pgdata:
    driver: local

networks:
  nw:
    driver: bridge